/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-8-25")
public class QuizType implements org.apache.thrift.TBase<QuizType, QuizType._Fields>, java.io.Serializable, Cloneable, Comparable<QuizType> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QuizType");

  private static final org.apache.thrift.protocol.TField QUIZ_FIELD_DESC = new org.apache.thrift.protocol.TField("quiz", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QuizTypeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QuizTypeTupleSchemeFactory());
  }

  public String quiz; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    QUIZ((short)1, "quiz");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // QUIZ
          return QUIZ;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.QUIZ, new org.apache.thrift.meta_data.FieldMetaData("quiz", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QuizType.class, metaDataMap);
  }

  public QuizType() {
  }

  public QuizType(
    String quiz)
  {
    this();
    this.quiz = quiz;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QuizType(QuizType other) {
    if (other.isSetQuiz()) {
      this.quiz = other.quiz;
    }
  }

  public QuizType deepCopy() {
    return new QuizType(this);
  }

  @Override
  public void clear() {
    this.quiz = null;
  }

  public String getQuiz() {
    return this.quiz;
  }

  public QuizType setQuiz(String quiz) {
    this.quiz = quiz;
    return this;
  }

  public void unsetQuiz() {
    this.quiz = null;
  }

  /** Returns true if field quiz is set (has been assigned a value) and false otherwise */
  public boolean isSetQuiz() {
    return this.quiz != null;
  }

  public void setQuizIsSet(boolean value) {
    if (!value) {
      this.quiz = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case QUIZ:
      if (value == null) {
        unsetQuiz();
      } else {
        setQuiz((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case QUIZ:
      return getQuiz();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case QUIZ:
      return isSetQuiz();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QuizType)
      return this.equals((QuizType)that);
    return false;
  }

  public boolean equals(QuizType that) {
    if (that == null)
      return false;

    boolean this_present_quiz = true && this.isSetQuiz();
    boolean that_present_quiz = true && that.isSetQuiz();
    if (this_present_quiz || that_present_quiz) {
      if (!(this_present_quiz && that_present_quiz))
        return false;
      if (!this.quiz.equals(that.quiz))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_quiz = true && (isSetQuiz());
    list.add(present_quiz);
    if (present_quiz)
      list.add(quiz);

    return list.hashCode();
  }

  @Override
  public int compareTo(QuizType other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetQuiz()).compareTo(other.isSetQuiz());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuiz()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.quiz, other.quiz);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QuizType(");
    boolean first = true;

    sb.append("quiz:");
    if (this.quiz == null) {
      sb.append("null");
    } else {
      sb.append(this.quiz);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QuizTypeStandardSchemeFactory implements SchemeFactory {
    public QuizTypeStandardScheme getScheme() {
      return new QuizTypeStandardScheme();
    }
  }

  private static class QuizTypeStandardScheme extends StandardScheme<QuizType> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QuizType struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // QUIZ
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.quiz = iprot.readString();
              struct.setQuizIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QuizType struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.quiz != null) {
        oprot.writeFieldBegin(QUIZ_FIELD_DESC);
        oprot.writeString(struct.quiz);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QuizTypeTupleSchemeFactory implements SchemeFactory {
    public QuizTypeTupleScheme getScheme() {
      return new QuizTypeTupleScheme();
    }
  }

  private static class QuizTypeTupleScheme extends TupleScheme<QuizType> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QuizType struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetQuiz()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetQuiz()) {
        oprot.writeString(struct.quiz);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QuizType struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.quiz = iprot.readString();
        struct.setQuizIsSet(true);
      }
    }
  }

}

