addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.10.0")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.13.1")
addSbtPlugin("com.github.sbt" % "sbt-release" % "1.5.0")
addSbtPlugin("com.twitter" % "scrooge-sbt-plugin" % "22.1.0")
addSbtPlugin("com.gu" % "sbt-scrooge-typescript" % "4.0.2")
addSbtPlugin("ch.epfl.scala" % "sbt-version-policy" % "3.2.1")
