//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var quiz_ttypes = require('./quiz_types')


var ttypes = module.exports = {};
if (typeof contentatom === 'undefined') {
  contentatom = {};
}
ttypes.EventType = {
  'PUBLISH' : 0,
  'UPDATE' : 1,
  'TAKEDOWN' : 2
};
contentatom.AtomData = module.exports.AtomData = function(args) {
  this.quiz = null;
  if (args) {
    if (args.quiz !== undefined) {
      this.quiz = args.quiz;
    }
  }
};
contentatom.AtomData.prototype = {};
contentatom.AtomData.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.quiz = new quiz_ttypes.QuizType();
        this.quiz.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

contentatom.AtomData.prototype.write = function(output) {
  output.writeStructBegin('AtomData');
  if (this.quiz !== null && this.quiz !== undefined) {
    output.writeFieldBegin('quiz', Thrift.Type.STRUCT, 1);
    this.quiz.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

contentatom.ContentAtomEvent = module.exports.ContentAtomEvent = function(args) {
  this.id = null;
  this.url = null;
  this.atomType = null;
  this.eventType = null;
  this.data = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
    if (args.url !== undefined) {
      this.url = args.url;
    }
    if (args.atomType !== undefined) {
      this.atomType = args.atomType;
    }
    if (args.eventType !== undefined) {
      this.eventType = args.eventType;
    }
    if (args.data !== undefined) {
      this.data = args.data;
    }
  }
};
contentatom.ContentAtomEvent.prototype = {};
contentatom.ContentAtomEvent.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.url = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.atomType = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.eventType = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRUCT) {
        this.data = new ttypes.AtomData();
        this.data.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

contentatom.ContentAtomEvent.prototype.write = function(output) {
  output.writeStructBegin('ContentAtomEvent');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.url !== null && this.url !== undefined) {
    output.writeFieldBegin('url', Thrift.Type.STRING, 2);
    output.writeString(this.url);
    output.writeFieldEnd();
  }
  if (this.atomType !== null && this.atomType !== undefined) {
    output.writeFieldBegin('atomType', Thrift.Type.STRING, 3);
    output.writeString(this.atomType);
    output.writeFieldEnd();
  }
  if (this.eventType !== null && this.eventType !== undefined) {
    output.writeFieldBegin('eventType', Thrift.Type.I32, 4);
    output.writeI32(this.eventType);
    output.writeFieldEnd();
  }
  if (this.data !== null && this.data !== undefined) {
    output.writeFieldBegin('data', Thrift.Type.STRUCT, 5);
    this.data.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

