//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
QuizType = module.exports.QuizType = function(args) {
  this.quiz = null;
  if (args) {
    if (args.quiz !== undefined) {
      this.quiz = args.quiz;
    }
  }
};
QuizType.prototype = {};
QuizType.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.quiz = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QuizType.prototype.write = function(output) {
  output.writeStructBegin('QuizType');
  if (this.quiz !== null && this.quiz !== undefined) {
    output.writeFieldBegin('quiz', Thrift.Type.STRING, 1);
    output.writeString(this.quiz);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

