name: Release

on:
  workflow_dispatch:

jobs:
  scala-maven-release:
    name: Maven Release
    uses: guardian/gha-scala-library-release-workflow/.github/workflows/reusable-release.yml@v1
    permissions: { contents: write, pull-requests: write }
    secrets:
      SONATYPE_TOKEN: ${{ secrets.AUTOMATED_MAVEN_RELEASE_SONATYPE_TOKEN }}
      PGP_PRIVATE_KEY: ${{ secrets.AUTOMATED_MAVEN_RELEASE_PGP_SECRET }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.AUTOMATED_MAVEN_RELEASE_GITHUB_APP_PRIVATE_KEY }}

  typescript-npm-release:
    name: NPM Release
    needs: scala-maven-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1.1.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      # Trusted publishing requires npm CLI v11.5.1 or later:
      - run: npm install -g npm@11.6.1
      - name: Release Typescript to NPM
        run: |
          sbt "project typescriptClasses" "releaseNpm ${{ needs.scala-maven-release.outputs.RELEASE_VERSION }}"
        env:
          RELEASE_TYPE: ${{ needs.scala-maven-release.outputs.RELEASE_TYPE }}
