name: Snyk
on:
  push:
    branches:
      - main
      - integrate-snyk-5514a8892997f4b7
  workflow_dispatch: 
jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: <SNYK_ORG_ID>
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
