# This action is just a test
name: Snyk (test)

on: push

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@js/npm-install
    with:
      DEBUG: true
      ORG: guardian-test
      SKIP_NODE: false
      NODE_PACKAGE_JSON_FILES_MISSING_LOCK: ./package.json
      NODE_VERSION_OVERRIDE: 16
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
